### PR TITLE
Scroll Up!

### PR DESCRIPTION
**Pull request by mondras**
- A little fix to scroll up the elements so we don't end up with this terrible "middle post that I can't read because the screen is over" behavior: http://d.pr/i/Rd8c 
- I also added an extra 100 pixels to the top so that posts are not hidden by some sites headers such as facebook.
- Deleted some unused whitespaces in the .coffee scripts, let's save the planet by not having extra whitespaces :dog:

### CODE REVIEW

**Comment by mondras** [comment]
Hi @k4v! 

Thanks for sharing your fork! 

That's how I initially did it but I think it's good to have less plugins (IMHO they shouldn't be using jQuery at all haha), but since I like simplicity I think it's better to have one line that gives you the result.

what do you think? @lucasvo

**Comment by thomasst** [comment]
I don't like it, because it scrolls the page with every link. Can you make it so that it scrolls down an entire page when you reach the bottom 100px of the screen?

**Comment by mondras** [comment]
I could, but I actually like the way it behaves so I can keep my eyes fixed in a place and get the content there, it makes it feel like a "next" button.

I guess we just like different things haha

**Comment by thomasst** [comment]
Disagree. Let's say you're on craigslist and saw a specific link at the bottom of the page you want to hover on, then it's way easier to do this if the page doesn't scroll, as you can focus your eyes on that link. It also strains my eyes more if the page scrolls every time. Besides, it currently breaks Google Instant because it scrolls to the results while you're typing a query.

**Comment by mondras** [comment]
I disagree on your first point. Looking at the bottom link defeats the purpose of this.

For the second issue, we could do start doing that on the second result, thanks for pointing that out @thomasst !

**Pull request closed without merging**
